/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "OhTP",
  "tagline": "Dinosaurs are cool",
  "url": "https://ohtp.xyz",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/asean/RiderProjects/TestDoc/my-website/sidebars.js",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": false,
        "theme": {
          "customCss": "/home/asean/RiderProjects/TestDoc/my-website/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    null
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "logo": {
        "alt": "OHTP logo",
        "width": 80,
        "height": 80,
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "documentation",
          "position": "right",
          "label": "Documentation"
        },
        {
          "to": "/pricing",
          "label": "Pricing",
          "position": "right"
        },
        {
          "href": "https://github.com/facebook/docusaurus",
          "label": "Sign Up",
          "position": "right",
          "className": "button button--lg"
        },
        {
          "href": "https://github.com/facebook/docusaurus",
          "label": "Login",
          "position": "right",
          "className": "button button--secondary button--lg"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/documentation"
            },
            {
              "label": "Quickstart",
              "to": "/docs/documentation"
            },
            {
              "label": "Sample",
              "to": "/docs/documentation"
            }
          ]
        },
        {
          "title": "Support",
          "items": [
            {
              "label": "Contact us",
              "to": "/contact"
            },
            {
              "html": "\n                    <a href=\"mailto:support@ohtp.xyz\" >\n                      <p>support@ohtp.xyz</p>\n                    </a>\n                  "
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Terms of Service",
              "to": "/docs/documentation"
            },
            {
              "label": "Privacy Policy",
              "to": "/docs/documentation"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 OhTP, LLC."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": []
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
