export default {
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1df93b7f': [() => import(/* webpackChunkName: '1df93b7f' */ '@site/src/pages/index.tsx'), '@site/src/pages/index.tsx', require.resolveWeak('@site/src/pages/index.tsx')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '4a25d6cc': [() => import(/* webpackChunkName: '4a25d6cc' */ '@site/src/pages/pricing.tsx'), '@site/src/pages/pricing.tsx', require.resolveWeak('@site/src/pages/pricing.tsx')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '6f1264a4': [() => import(/* webpackChunkName: '6f1264a4' */ '/home/asean/RiderProjects/Otp/Otp.Site/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/home/asean/RiderProjects/Otp/Otp.Site/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/home/asean/RiderProjects/Otp/Otp.Site/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  '7ab81c4a': [() => import(/* webpackChunkName: '7ab81c4a' */ '@site/docs/documentation.md'), '@site/docs/documentation.md', require.resolveWeak('@site/docs/documentation.md')],
  '8b3a140c': [() => import(/* webpackChunkName: '8b3a140c' */ '@site/src/pages/contact.tsx'), '@site/src/pages/contact.tsx', require.resolveWeak('@site/src/pages/contact.tsx')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  '9bd08d69': [() => import(/* webpackChunkName: '9bd08d69' */ '/home/asean/RiderProjects/Otp/Otp.Site/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/home/asean/RiderProjects/Otp/Otp.Site/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/home/asean/RiderProjects/Otp/Otp.Site/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],};
