name: api

on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - auto_merge_enabled
      - closed
    paths:
      - 'Otp.Api/**'
      - 'Otp.Application/**'
      - 'Otp.Core/**'
      - 'Otp.Infrastructure/**'

env:
  PROJECT_NAME: Otp.Api
  ARTIFACT_NAME: drop
  PUBLISH_PATH: ${{ github.workspace }}/artifact

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_NAME }}
      - name: Build ${{ env.PROJECT_NAME }}
        run: dotnet build --no-restore ${{ env.PROJECT_NAME }}
      - name: Publish ${{ env.PROJECT_NAME }}
        if: ${{ github.event_name == 'workflow_dispatch' || github.head_ref == 'main' }}
        run: dotnet publish --no-restore -c Release -o ${{ env.PUBLISH_PATH }} ${{ env.PROJECT_NAME }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'workflow_dispatch' || github.head_ref == 'main' }}
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_PATH }}
