name: api

on:
  workflow_dispatch:
  push:
    paths:
      - 'Otp.Api/**'
      - 'Otp.Application/**'
      - 'Otp.Core/**'
      - 'Otp.Infrastructure/**'
  pull_request:
    paths:
      - 'Otp.Api/**'
      - 'Otp.Application/**'
      - 'Otp.Core/**'
      - 'Otp.Infrastructure/**'
        
jobs: 
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
    