name: infra

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/infra.yaml'
            - '!.github/workflows/**'
            - 'infra/**'
    pull_request:
        types:
            - synchronize
            - auto_merge_enabled
            - opened
        paths:
            - '.github/workflows/infra.yaml'
            - '!.github/workflows/**'
            - 'infra/**'

env:
    DOTNET_VERSION: 6.0.x

permissions:
    id-token: write
    contents: read

jobs:
    preview:
        name: pulumi preview
        uses: ./.github/workflows/pulumi.yaml
        with:
            command: preview
        secrets:
            azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
            azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            aws-role-id: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            pulumi-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

    up:
        name: pulumi up
        uses: ./.github/workflows/pulumi.yaml
        needs: 
            - preview
        with:
            command: up
        secrets:
            azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
            azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            aws-role-id: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            pulumi-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
