name: infra

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/infra.yaml'
            - '!.github/workflows/**'
            - 'infra/**'
    pull_request:
        types:
            - synchronize
            - auto_merge_enabled
            - opened
        paths:
            - '.github/workflows/infra.yaml'
            - '!.github/workflows/**'
            - 'infra/**'

env:
    DOTNET_VERSION: 6.0.x

permissions:
    id-token: write
    contents: read

jobs:
    preview:
        name: preview
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: ${{ env.DOTNET_VERSION }}
            -   name: Configure Azure Credentials
                uses: azure/login@v1
                with:
                    client-id: ${{ secrets.AZURE_CLIENT_ID }}
                    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                    aws-region: ${{ secrets.AWS_REGION }}
            -   uses: pulumi/actions@v3
                with:
                    command: preview
                    work-dir: infra
                    comment-on-pr: true
                    stack-name: aws-dev
                    upsert: true
                    cloud-url: azblob://pulumi?storage_account=stodeploymentdata
                env:
                    PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
    up:
        name: up
        runs-on: ubuntu-latest
        needs:
            - preview
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: ${{ env.DOTNET_VERSION }}
            -   name: Configure Azure Credentials
                uses: azure/login@v1
                with:
                    client-id: ${{ secrets.AZURE_CLIENT_ID }}
                    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                    aws-region: ${{ secrets.AWS_REGION }}
            -   uses: pulumi/actions@v3
                with:
                    command: up
                    work-dir: infra
                    comment-on-pr: true
                    stack-name: aws-dev
                    cloud-url: azblob://pulumi?storage_account=stodeploymentdata
                env:
                    PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
