name: web

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ui.yaml"
      - 'Otp.Web/**'
  pull_request:
    types:
      - synchronize
      - auto_merge_enabled
      - opened
    paths:
      - ".github/workflows/ui.yaml"
      - 'Otp.Web/**'

env:
  PROJECT_NAME: Otp.Web
  NODE_VERSION: 14

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: ${{ env.PROJECT_NAME }}/yarn.lock
      - name: Install packages
        run: yarn install --fronzen-lockfile
        working-directory: ${{ env.PROJECT_NAME }}
      - name: Build ${{ env.PROJECT_NAME }}
        run: yarn build
        working-directory: ${{ env.PROJECT_NAME }}